kind: Deployment
apiVersion: apps/v1
metadata:
   name: awan
spec:
   replicas: 2
   selector:
    matchLabels:
     app: awan
   template:
      metadata:
        labels:
          app: awan
      spec:
       containers:
        - name: awan
          image: abdhfz93/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
